# Configurazione per MainaAudit
title: MainaAudit üõ°Ô∏è
description: Professional Endpoint Security Auditor
remote_theme: pages-themes/hacker@v0.2.0 # Forza l'uso del tema Hacker
show_downloads: true

# Fondamentale per evitare crash con i tuoi template .md
exclude:
  - templates/
  - data/
  - output/
  - Invoke-Audit.ps1
  - assets/logo.png
